### ISSUE TITLE
Make columnDefs an observable

### ISSUE THREAD

**Issue by ghost** [Knockout-Contrib/KoGrid#37] opened 2012-05-09 19:24 UTC
I am working on a page where having the ability to add and remove columns would be very handy. I was thinking about implementing this in the grid (and doing a pull request). Was there a reason that you didn't make it an observable array?

Thanks

**Comment by ericmbarnard** [comment] 2012-06-05 03:10
@mgalfapair 

Sorry for the delay on this, I've switched jobs and am just now getting a chance to work through my GH issues. The reason that this wasn't initially done is that the instance of the `Grid` object is heavily dependent upon the column collection that it was initialized with. An example would be how we dynamically build row templates and header row cells based upon the column collection. It is not super easy at this point to just trigger a rebuild of those whenever the column collection changes.

I agree that this needs to be done, but it wasn't something that was trivial to implement on my last feature sprint.

**Comment by athingisathing** [comment] 2012-08-07 21:02
Is there a work around... my whole site would require columns to change on the fly... I'm also going to try and use flex.js with this grid and see what it does, but it would work best with dynamic columns.

**Comment by orneryd** [comment] 2012-08-19 03:24
I have implemented this feature, basically the columndefs is now an observable. if you want to add/remove columns then you need to modify the underlying observable so the knockout subscription fires to re-render the columns.

added in commit https://github.com/Crash8308/sKoGrid/commit/31584f10f4a0e900e77542ae910b1d17a8054472

my fork: https://github.com/Crash8308/sKoGrid

**Comment by orneryd** [comment] 2012-08-30 19:58
duplicate of issue 11. closing this one

**Closed as completed by orneryd** 2012-08-30 19:58 UTC
Labels: Todo
