### ISSUE TITLE
Editable Grid?

### ISSUE THREAD

**Issue by iGrog** [Knockout-Contrib/KoGrid#13] opened 2012-02-15 14:53 UTC
Nice Grid!
But, what's about editable cell templates? Any plans to allow checkboxes, dropdown lists, inputs and textareas?
It would be nice! :)

**Comment by ericmbarnard** [comment] 2012-02-15 14:57
@iGrog 

Since cells and rows are directly bound to your own javascript objects, you should be able to create your own editable cell templates very easy.

https://github.com/ericmbarnard/KoGrid/wiki/Custom-Templates

If you are running into bugs with this let me know, otherwise those instructions should help you see how to use an `<input/>` inside a cell template (or any other valid html that you would like)

**Comment by iGrog** [comment] 2012-02-16 07:43
Thanks, I'll try.
But can you say, please, is it possible to change row/cell template from 'view-template' to 'edit-template' on e.g. mouse-double-click on row?

**Comment by iGrog** [comment] 2012-02-16 09:21
Please, see the following jsfiddle: http://jsfiddle.net/rg46Y/

If I edit values in corresponding &lt; input&gt;'s, no original data change. What do I wrong?

**Comment by ericmbarnard** [comment] 2012-02-16 14:09
You need to make the properties that you want to be editable `ko.observable`

http://jsfiddle.net/rg46Y/1/

As far as your question about toggling between edit/view modes in a cell ... that should be able to be done completely via cell templates. I don't currently have an example, but you can use `focus` and `visible` bindings to toggle between whether the cell has an `input` tag showing or just a `div`

**Comment by iGrog** [comment] 2012-02-20 09:02
Thanks. I'll use ko.mapping plugin, and it works :)
But what's about switching templates?
Please see http://jsfiddle.net/LJq3x/1/
How this switching can be done?

And one more question? How is it possible to place in `filter row` some kind of dropdown list?

**Comment by orneryd** [comment] 2012-08-19 20:25
just use the row template and bind readonly to !isSelected() from your object viewmodel.

**Comment by orneryd** [comment] 2012-08-30 19:59
Closing this as it is working as intended.

**Closed as completed by orneryd** 2012-08-30 19:59 UTC
Labels: FAQ
