### ISSUE TITLE
Memory Leeeeeeeeeeeeeeak

### ISSUE THREAD

**Issue by OmarKhanfer** [Knockout-Contrib/KoGrid#59] opened 2012-07-18 16:05 UTC
When I move the scroll up and down the memory usage of the browser increasing I dont know why any solution.

**Comment by ericmbarnard** [comment] 2012-08-27 01:18
@OmarKhanfer 

Can you let us know the browser version?

**Comment by OmarKhanfer** [comment] 2012-08-27 03:46
Dear Eric,

Its IE8.

Thanks and Regards
Omar

**Comment by ericmbarnard** [comment] 2012-08-27 14:22
I'm going to mark as a duplicate of Issue #58 and close it

**Closed as completed by ericmbarnard** 2012-08-27 14:22 UTC
