### ISSUE TITLE
enableColumnResize parameter is not working

### ISSUE THREAD

**Issue by igoryan-k** [Knockout-Contrib/KoGrid#165] opened 2012-12-17 17:14 UTC
Hi
I wanted to disable the column resizing inside KOgrid and noted that there is a parameter for that in koGrid options - enableColumnResize. I tried to set to to false, but it didn't work, I was still able to resize. 
I checked the KoGrid code, the enableColumnResize parameter is saved as enableResize in internal column definition.

```
 var column = new kg.Column({
                    colDef: colDef, 
                    index: i, 
                    headerRowHeight: self.config.headerRowHeight,
                    sortCallback: self.sortData, 
                    resizeOnDataCallback: self.resizeOnData,
                    enableResize: self.config.enableColumnResize
                }, self);
                cols.push(column);
```

But the enableResize is never used throughout the code. 
I guess gripOnMouseDown, onMouseMove and gripOnMouseUp will need to be changed.

**Comment by orneryd** [comment] 2012-12-18 00:51
duplicate of  #164, and will be fixed in next build

**Closed as completed by orneryd** 2012-12-18 00:51 UTC
